name: "sputnik-test"
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    command: "-c 'fsync=off' -c 'full_page_writes=off'"
    ports:
      - "${TEST_PG_PORT}:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 100ms
      retries: 10
